######################################################################################
# docker-compose[nexus]
#
######################################################################################
version: '2'
services:

  redmine:
    # ビルドイメージ
    build: ./build
    # タグ名
    image: develop/nexus:latest
    # コンテナ名
    container_name: nexus
    # ポートフォワード
    ports:
      - 10084:8080
    # ボリュームマウント
    volumes:
      # データストア
      - "/private/opt/var/nexus:/opt/sonatype/sonatype-work/nexus3"
      # ログファイル
      - "/private/opt/log/nexus:/var/log/nexus"
    # 環境変数
    environment:
      - JAVA_HOME=/usr/lib/jdk1.8.0_144
      - PATH=${PATH}:/usr/lib/jdk1.8.0_144/bin
    # 処理変数
    args:
      - SONATYPE_DIR=/opt/sonatype
      - NEXUS_VERSION=3.5.1-02
      - NEXUS_DOWNLOAD_URL=https://download.sonatype.com/nexus/3/nexus-${NEXUS_VERSION}-unix.tar.gz
      - NEXUS_HOME=${SONATYPE_DIR}/nexus
      - NEXUS_DATA=${SONATYPE_DIR}/sonatype-work/nexus3
      - NEXUS_LOG=/var/log/nexus
      - JAVA_VERSION_MAJOR=8 \
      - JAVA_VERSION_MINOR=144 \
      - JAVA_VERSION_BUILD=01 \
      - JAVA_DOWNLOAD_HASH=090f390dda5b47b9b721c7dfaa008135
      - JAVA_DOWNLOAD_URL=http://download.oracle.com/otn-pub/java/jdk/${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-b${JAVA_VERSION_BUILD}/${JAVA_DOWNLOAD_HASH}/server-jre-${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-linux-x64.tar.gz
