######################################################################################
# docker-compose[nexus]
#
######################################################################################
version: '2'
services:

  nexus:
    # ビルドイメージ
    build: ./build
    # タグ名
    image: develop/nexus:16.04
    # コンテナ名
    container_name: nexus
    # リソース制限
    mem_limit: 256000000
    memswap_limit: 2000000000
    # ポートフォワード
    ports:
      - 10084:8080
    # ボリュームマウント
    volumes:
      # データストア
      - "/private/opt/var/nexus:/opt/sonatype/sonatype-work/nexus3"
      # ログファイル
      - "/private/opt/log/nexus:/var/log/nexus"
    # 環境変数
    environment:
      - JAVA_HOME=/usr/lib/jdk1.8.0_144
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin/:/usr/bin:/sbin:/bin:/usr/lib/jdk1.8.0_144/bin
      - TZ=Asia/Tokyo
      - LANG=ja_JP.UTF-8
      - L C_ALL ja_JP.UTF-8
      - LC_CTYPE ja_JP.UTF-8
